### ISSUE TITLE
2019-11-05 check in

### ISSUE THREAD

**Issue by MelissaBradshaw** [MelissaBradshaw/ALLP#11]
@zmstell @echristie111 @cmccraw @xsun93 @samanthalepak 

For tonight we will:
1. Revisit the wireframe and see check in with Bill about any updates or questions
2. Discuss -ographies with Zach
3. Check in with Ericka and Caroline about workflow and encoding
4. set priorities for next week

See you soon!

**Comment by MelissaBradshaw** [comment]
To do for 11/12: 
Everyone:
-figure out better name for resources/scholarship tab (where we keep links to scholarship on Lowell, links to books, articles, websites, etc.)
MB
-what do I want to call roles? figure out titles to go under credits
-need tenth letter, from George Brett or Edward Marsh
-find summer 2018 prioritization sheet which shows which letters Xixi and Wren transcribed

**Comment by cmccraw** [comment]
@MelissaBradshaw yes! My ulterior motive for figuring out roles is to determine what to put on application CVs... 😄 😄 

Had a super successful chat with Becca, will update everyone shortly!
