### ISSUE TITLE
ALLP: Ographies – Dev Log 

### ISSUE THREAD

**Issue by MelissaBradshaw** [MelissaBradshaw/ALLP#4]
@zmstell, the prosopography looks great. I'm so pleased. Thank you for leaving space for us to add bio-notes. As @samanthalepak writes them, perhaps you can pull out sentences to use in the prosopography. 

I'd also like to add affiliations. That would look like this: 

```
<person xml:id="Amy-Lowell">
<persName>Amy Lowell</persName>
<affiliation corresp="imagist" from="1913" to="1925"></affiliation>
</person>
```

Lowell's affiliation ends in 1925 because she dies, so I'd need to think about how we'd define the end date for other figures.

I will add an affiliation category to the ALLP prosopography spreadsheet for tags like imagist, vorticist, etc. so you can see who needs this additional information.

Q: do we keep this all in one prosopography, or do we have a separate one for people (ALLPPerson.xml) and groups (ALLPOrg.xml) like imagist, but also journals, like Poetry.

@cmccraw @echristie111 this might be helpful for you too.

**Comment by cmccraw** [comment]
@zmstell https://www.wwp.northeastern.edu/outreach/seminars/_current/presentations/contextual_encoding/contextual_encoding.xml

**Comment by zmstell** [comment]
### 10/30 - 11/5

- Began expanding the ographies working from the initial personography that I established a few weeks ago 

- After reading “Encoding Contextual Information,” I found that there are a few places that we can add a few more fields to the personogrphy to enrich the subjects, but perhaps we don’t have to change all of them.  

**- Elements/Attributes to possibly add (to whom it may concern):** 

__Personography__ 

- <langKnowledge> 

- <socecStatus>  

                         I feel as though this is a big factor and will highlight the social dynamics 
                         behind ALLP more precisely 

- <trait type=”PHYSICAL_CHARCTERISTIC”>            

                         Perhaps this is important for only a few individuals 

- <state type=”SOME_GENERAL_CHARACTERSIC”> 

                          Example: Marital status 

- <affiliation> 

- <faith> 

- <education> 

                            Might have an evidence attribute, labelled either internal (evidence 
                            offered in the text), external (evidence offered outside the text in some 
                            related source), or conjecture (debated among scholars). 

- <residence> 

                            Could have multiple tags 

- <event> 

_Placeoography_ 

- <region> 

- <geo> (coordinates), usually wrapped in <location> tags 

- <address> 

_Eventorgraphy_ 

_Other Ographies_ 

- <listOrg> 

                              Places that people would be affiliated with 

                              Each would have their own unique id and description 

- <listBibl> 

                              <bibl xml:id=”UNIQUE_ID”> 

                              What other entities are we trying to capture? 

**Interpretive stuff**

_Interpretive keywords and themes_ 

- Interpretive classifications 

                                Is there any way we would want to categorize the letters? 

_Associating interpretations and classifications with the text_ 
                                ...

**Giving Credit & Tracking Responsibility**

- Transcription                           

- Proofing of transcription 
                   
- Encoding                             

- Proofing of encoding 

**General**
- Are people on this project mentioned in the personography? 

- The viaf can be referenced in the personography 

- The persistent link to the Hollis documents can be mentioned in the bibliography and then point to the people that they pertain to.  

**Work in Spreadsheets** 

- Accounted for all individuals mentioned in first string, separating them by mentioned (blue) and recipients (green). 

- If the individual was a poet or editor/critic/etc., I made sure to also account for them in those sections as well as highlight them. 

- AllpPersonography.xml also now reflects “Recipients and Mentioned – First String,” viaf links and all.

**Comment by cmccraw** [comment]
@zmstell this all looks so awesome! In thinking about workflow, I wonder if we should have the first sheet of the Ographies spreadsheet be a list of items to be added— since my experience is that as encoding continues, encoders are constantly coming across more things to add to Ographies! Then @MelissaBradshaw could review them, and the Ographer (??) could relegate the keepers to the appropriate Ography sheet. Maybe we can talk more about this in class tonight!

**Comment by MelissaBradshaw** [comment]
@zmstell @cmccraw @echristie111 Let's talk about this tonight. We don't want to make or -ographies overly complicated, but Zach's point that these then become searchable categories is a good one. How many people in these letters spoke French, for example? If that is discoverable information, that would be important to someone doing research on imagist debt to French symbolist movement, for example.
