### ISSUE TITLE
Encoding questions/decisions

### ISSUE THREAD

**Issue by MelissaBradshaw** [MelissaBradshaw/ALLP#5]
@echristie111 @cmccraw @zmstell 

Tags for titles: 

- for journals/magazines: <title level=“j”> The Little Review</title>  (“j” is for journal; 

- monograph will be <title level="m"> Men, Women, and Ghosts</title>; 

- poem will be <title level="a"> Patterns</title> (a=analytic)

**Comment by cmccraw** [comment]
@echristie111 @cmccraw @zmstell @MelissaBradshaw 

Updates from chatting with Becca:

+ Having lots of -ographies is fine/great! I'd imagine that ours would include the following:
   + Personography
   + Placeography
   + Orgography (incl. publishers, families ("The Aldingtons"), socieities)
   + Eventography (WWI, surgeries, etc.)
   + Bibliography (periodicals, books, poems)
   + Keyword/subject-ography (need to figure out name!); would include "Pound feud," "copyright," etc., to be referenced in TEI header

Becca says that collectively, these -ographies can be referred to as a "Site Index."

Also, for non-persName or placeName elements, rf string is a great alternative (for -ography content that isn't already determined by TEI standards). 

+ For referencing multiple people ("The Aldingtons"), we'd need to establish "The Aldingtons" in the orgography (this makes sense when you think about how families or other groups of people might include names that we don't know, or lots of names; see spreadsheet for details about including individuals in the orography entry: https://docs.google.com/spreadsheets/d/1Sh_kSRuQHWhM0vyfdfDrVIvMppplgCD20oWPRuNyJ8M/edit#gid=0)

+ For keywords, it will be easiest to create a statement in the TEI header encodingDesc; statement could say ```<p> This letter contains references to keyword, keyword, keyword</p>``` and then tag each keyword in a ref string, linking back to keyword-ography. 

+  For transactions, could use rf as well, but will need to be very clear in attributes about how differentiated from -ography content. We should also research the currency TEI element ("measure"), potentially using "num" element linked to ref string. Should also decide if we want to create standardized attributes like sending vs. receiving? Any other details about a transaction that we want to encode?

+ For zingers, look in guidelines to see which element related to the "quote" element makes the most sense for our purposes. (See Nelson project's mode of documenting "wit")

+ For tagging poems, look into ```bibl``` for titles of works (bibl type = poem)
---
_Resources:_
+ Ref string: https://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-rs.html
+ Quote element (for zingers): https://www.tei-c.org/release/doc/tei-p5-doc/en/html/CO.html#COHQQ
+ Digital Mitford Site Index (so final product of all combined -ographies): https://digitalmitford.org/si.xml
+ Bibl element (for poems and publications): https://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-bibl.html
+ Orgs section from Mitford Codebook: https://docs.google.com/document/d/1r-8NGPJL1pZ20pnfvoX5OT0DkcDi-NBp5urJiZwx1sY/pub#id.26in1rg
+ Titles section from Mitford Codebook: https://docs.google.com/document/d/1r-8NGPJL1pZ20pnfvoX5OT0DkcDi-NBp5urJiZwx1sY/pub#id.26in1rg
